In [11]:
import numpy as np
import numpy.linalg as la
mat = np.loadtxt("matrix.txt", dtype=int,skiprows=1)

Question #1

In [12]:
def prob1(mat):
    N = len(set(list(mat[:,0]) + list(mat[:,1])))
    adj = np.zeros((N,N))
    for i,node in enumerate(mat):
        adj[node[0],node[1]] = 1
    return mat,adj,N

graph, adj,N = prob1(mat)
print(graph)
print(adj)

[[0 7]
 [1 0]
 [3 0]
 [3 2]
 [3 6]
 [4 0]
 [4 5]
 [4 6]
 [5 0]
 [5 6]
 [6 0]
 [7 0]]
[[ 0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  0.  1.  1.  0.]
 [ 1.  0.  0.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]]


Question #2

In [13]:
def prob2(mat):
    O,A,N = prob1(mat)
    for i,links in enumerate(A):
        if np.sum(links) == 0.0:
            A[i] = np.array([1 for j in links])
    D = np.diag(np.array([sum(row) for row in A]))
    K = np.transpose(la.inv(D) @ A)
    return O,A,K,N
    
Original,Adj,K,N = prob2(mat)
print(K)

[[ 0.          1.          0.125       0.33333333  0.33333333  0.5         1.
   1.        ]
 [ 0.          0.          0.125       0.          0.          0.          0.
   0.        ]
 [ 0.          0.          0.125       0.33333333  0.          0.          0.
   0.        ]
 [ 0.          0.          0.125       0.          0.          0.          0.
   0.        ]
 [ 0.          0.          0.125       0.          0.          0.          0.
   0.        ]
 [ 0.          0.          0.125       0.          0.33333333  0.          0.
   0.        ]
 [ 0.          0.          0.125       0.33333333  0.33333333  0.5         0.
   0.        ]
 [ 1.          0.          0.125       0.          0.          0.          0.
   0.        ]]


Question #3

In [15]:
def prob3(mat,d=0.85,tol=0.00001):
    O,A,K,N = prob2(mat)
    p0 = list(np.random.randn(N))
    p1 = list(d*K@p0 + ((1-d)/N)*np.ones(N))
    p = [p0,p1]
    t = 1
    i = 0
    while la.norm(np.array(p[t])-np.array(p[t-1])) > tol and i < 1000:
        i = i + 1
        ptp1 = list(d*K@np.array(p[t]) + ((1-d)/N)*np.ones(N))
        p.append(ptp1)
        t = t + 1
    error = la.norm(np.array(p[-1])-np.array(p[-2]))
    return np.array(p[-1]),error
px,error = prob3(mat)
print("Long-Run Probability Matrix  :")
print(px)
print("-------------------------------------------------------------------------------")
print("Error  :    ",error)

Long-Run Probability Matrix  :
[ 0.43869123  0.02171029  0.02786154  0.02171029  0.02171029  0.02786154
  0.04585394  0.39459198]
-------------------------------------------------------------------------------
Error  :     8.69295389199e-06


Question #4

In [16]:
def prob4(mat,d=0.85,tol=0.00001):
    O,A,K,N = prob2(mat)
    E = np.ones((N,N))
    B = d*K + ((1-d)/N)*E
    eigs,vecs = la.eig(B)
    lamb, lvec = np.max(eigs), vecs[:,np.argmax(eigs)]
    return lvec*-0.594

prob4(mat)

array([ 0.43844869,  0.0216982 ,  0.02784603,  0.0216982 ,  0.0216982 ,
        0.02784603,  0.04582841,  0.39437959])

Question #5

In [22]:
import pandas as pd

def mapper(A):
    B = -1*np.ones(A.shape)
    c1 = 0
    for i in range(0,len(A)):
        B[i,0] = c1
        k = 0
        for j in range(0,i):
            if A[i,0] == A[j,0]:
                B[i,0] = B[j,0]
                k = k + 1
        if k == 0:
            c1 = c1 + 1
    c2 = 0
    for i in range(0,len(A)):
        k = 0
        for j in range(0,len(A)):
            if A[i,1] == A[j,0]:
                B[i,1] = B[j,0]
                k = k + 1
        if k == 0:
            B[i,1] = c1
            c1 = c1 + 1
    C = B.astype(int)
    return C

def prob5(filename):
    ncaa_df = pd.read_csv("ncaa2013.csv")
    ncaa_str = np.array(ncaa_df)
    ncaa = mapper(ncaa_str)
    longr = prob3(ncaa,d=0.7)
    return longr

Rank,eig = prob5("ncaa2013.csv")

In [23]:
print(np.sum(Rank))

1.00023785551


In [ ]:
,