In [1]:
import numpy as np
from scipy import linalg as la
import pickle

Question #1

In [119]:
def matrix_gen(m,n):
    Rm = np.arange(m)
    Rn = np.arange(n)
    return np.array([[(10+10)*np.random.random() - 10 for i in Rn] for j in Rm])

def M_Gram_Schmidt(A):
    m,n = len(A),len(A[0])
    Q = A.copy()
    r1 = list(np.arange(0,n))
    R = np.array([[0.0 for i in r1] for j in r1])
    for i in np.arange(0,n):
        R[i,i] = la.norm(Q[:,i])
        Q[:,i] = Q[:,i] / R[i,i]
        for j in np.arange(i+1,n):
            R[i,j] = np.dot(Q[:,j],Q[:,i])
            Q[:,j] = Q[:,j] - R[i,j]*Q[:,i]
    return A,Q,R


A,Q,R = M_Gram_Schmidt(matrix_gen(4,4))
print("Base Matrix (Randomly Generated):")
print(A)
print("---------------------------------")
print("Results:")
print("Orthonormal Component (Q):")
print(Q)
print("Upper-Triangular Component (R):")
print(R)
print("Check:")
print(la.norm(np.dot(Q,R) - A) < 0.00001)

Base Matrix (Randomly Generated):
[[ 3.15058854 -1.3693478  -4.4753564  -1.8236664 ]
 [-2.12407192 -8.09303142 -3.26178527 -3.44582122]
 [ 9.01196921 -3.12969293 -3.86191601  0.41154116]
 [ 1.93518736 -2.85011876  2.73728535 -1.07978251]]
---------------------------------
Results:
Orthonormal Component (Q):
[[ 0.3160108  -0.07877879 -0.56720754 -0.75644345]
 [-0.21304898 -0.94919063 -0.18047522  0.1451757 ]
 [ 0.90391988 -0.13782913 -0.01675556  0.40453829]
 [ 0.19410345 -0.27172448  0.80338257 -0.49301734]]
Upper-Triangular Component (R):
[[ 9.96987607 -2.09072617 -3.67888707  0.32024114]
 [ 0.          8.99551498  3.23711623  3.6510884 ]
 [ 0.          0.          5.39092319  0.7819086 ]
 [ 0.          0.          0.          1.57808665]]
Check:
True


Question #2

In [136]:
def determiner(n):
    A,Q,R = M_Gram_Schmidt(matrix_gen(n,n))
    det = 1
    for i in np.arange(n):
        det = det * R[i,i]
    return A,det

B,det = determiner(3)
print("Matrix:")
print(B)
print("Determinant:",det)

Matrix:
[[ 3.42878105  9.08052215 -4.47313495]
 [-7.22727906 -5.20568045  4.77067865]
 [ 5.28061768 -9.04787487  4.59122846]]
Determinant: 180.652534114


Question #3

In [146]:
m,n = 4,4
A,Q,R = M_Gram_Schmidt(matrix_gen(m,n))
b = np.array([np.random.random() for i in np.arange(n)])
x = np.array(np.dot(np.dot(np.linalg.inv(R),np.transpose(Q)),b))
print("Solution for x:")
print(x)
print("Check (Ax - b = 0):")
print(la.norm(np.dot(A,x) - b) < 0.0001)

Solution for x:
[ 0.07458389  0.06007275  0.00852546 -0.08017977]
Check (Ax - b = 0):
True


Question #4

In [241]:
def Householder(A):
    m,n = len(A),len(A[0])
    R = A.copy()
    Q = np.eye(m)
    for k in np.arange(n):
        u = R[k:,k].copy()
        u[0] = u[0] + (abs(u[0])/u[0])*la.norm(u)
        u = u / la.norm(u)
        R[k:,k:] = R[k:,k:] - 2*np.outer(u,np.dot(u,R[k:,k:]))
        Q[k:,:] = Q[k:,:] - 2*np.outer(u,np.dot(u,Q[k:,:]))
    return A,np.transpose(Q),R

A,Q,R = Householder(matrix_gen(4,4))
print("Base Matrix (Randomly Generated):")
print(A)
print("---------------------------------")
print("Results:")
print("Orthonormal Component (Q):")
print(Q)
print("Upper-Triangular Component (R):")
print(R)
print("Check:")
print(la.norm(np.dot(Q,R) - A) < 0.00001)

Base Matrix (Randomly Generated):
[[-5.36887257 -2.17398634 -7.81433585  5.66162161]
 [ 6.00831129 -3.81957801  9.1473898  -8.87174593]
 [-9.09585937  5.50252839 -2.7262812   9.35753904]
 [ 5.87884139  8.12363033  8.74719476 -3.19293413]]
---------------------------------
Results:
Orthonormal Component (Q):
[[-0.39772697 -0.24045268  0.24337904 -0.85132979]
 [ 0.44509669 -0.31503449 -0.76697202 -0.33822496]
 [-0.67382276  0.45077964 -0.58510876  0.02020733]
 [ 0.43550554  0.79983341  0.10083802 -0.40054104]]
Upper-Triangular Component (R):
[[  1.34988900e+01  -1.00527141e+00   1.28259272e+01  -1.38964277e+01]
 [  0.00000000e+00   1.07040184e+01   4.76458123e+00   3.09792664e+00]
 [  0.00000000e+00  -8.88178420e-16  -6.44041678e+00   2.38515373e+00]
 [  0.00000000e+00  -1.77635684e-15   2.22044605e-16  -3.51269176e-01]]
Check:
True


Question #5

In [254]:
def Hessenberg(A):
    m,n = len(A),len(A[0])
    H = A.copy()
    Q = np.eye(m)
    for k in np.arange(n-2):
        u = H[k+1:,k].copy()
        u[0] = u[0] + (abs(u[0])/u[0])*la.norm(u)
        u = u / la.norm(u)
        H[k+1:,k:] = H[k+1:,k:] - 2*np.outer(u,np.dot(u,H[k+1:,k:]))
        H[:,k+1:] = H[:,k+1:] - 2*np.outer(np.dot(H[:,k+1:],u),u)
        Q[k+1:,:] = Q[k+1:,:] - 2*np.outer(u,np.dot(u,Q[k+1:,:]))
        return A,H,np.transpose(Q)
    
A,H,Q = Hessenberg(matrix_gen(4,4))
print("Base Matrix (Randomly Generated):")
print(A)
print("---------------------------------")
print("Results:")
print("Orthonormal Component (Q):")
print(Q)
print("Hessenberg Component (H):")
print(H)
print("Check:")
print(la.norm(np.dot(np.dot(Q,A),np.transpose(Q)) - A) < 0.00001)

Base Matrix (Randomly Generated):
[[ 1.75712508  4.45939587 -3.84030482 -9.42549704]
 [ 6.89029943 -3.87771033  2.50553903 -4.3307958 ]
 [-1.35836876  4.6917102  -4.42024303  6.6056762 ]
 [ 4.22759209 -8.09928488 -4.13599781 -9.06611288]]
---------------------------------
Results:
Orthonormal Component (Q):
[[ 1.          0.          0.          0.        ]
 [ 0.         -0.84056845  0.16571151 -0.51573673]
 [ 0.          0.16571151  0.98508053  0.04643322]
 [ 0.         -0.51573673  0.04643322  0.85548792]]
Hessenberg Component (H):
[[  1.75712508   0.47626488  -3.48169243 -10.54159081]
 [ -8.19719018 -11.87481761   1.10318058   3.78169042]
 [  0.          -6.48192139  -3.2231678    2.54262926]
 [  0.           5.81544758  -5.98347624  -2.26608083]]
Check:
False
