In [1]:
import numpy as np

A = np.array([[1,5,3],[8,3,2],[9,5,4]])
b = np.array([40,38,21])
c = np.array([4,3,6])
x = np.array([1,1,1])
w = np.array([3,0,9])

Question 1-7

In [8]:
class Prob1(object):
    def __init__(self,b,c,w):
        self.b = b
        self.c = c
        self.w = w
        
    def cond_origin(self,A):
        x = np.zeros(A.shape[0])
        if (A@x < b).all() == True:
            return True
        else:
            raise ValueError("Origin Condition is not met")
    
    def slack_tracker(self,x):
        if self.cond_origin(A) != True:
            raise ValueError("Input matrix A is does not fit Ax < b for x = 0")
        index_x = [[i,x[i]] for i in range(len(x))]
        index_w = [[i+len(index_x),w[i]] for i in range(len(w))]
        index = np.array(index_x + index_w)
        basic_vals = []
        non_basic_vals = []
        for i in range(len(index)):
            if index[i,1] == 0:
                basic_vals.append(list(index[i]))
            else:
                non_basic_vals.append(list(index[i]))
        vals = non_basic_vals + basic_vals
        result = np.array([np.array(k) for k in vals])
        return result
    
    def tableau(self,A):
        if self.cond_origin(A) != True:
            raise ValueError("Input matrix A is does not fit Ax < b for x = 0")
        Abar = np.hstack((A,np.eye(A.shape[0])))
        cbar = np.hstack((-self.c,np.zeros(self.c.shape)))
        bT = np.array([[i] for i in b])
        T1 = np.hstack(([0],cbar,[1]))
        T2 = np.hstack((bT,Abar,np.zeros_like(bT)))
        T = np.vstack((T1,T2))
        return T
    
    def indexer(self,T):
        if self.cond_origin(A) != True:
            raise ValueError("Input matrix A is does not fit Ax < b for x = 0")
        p_index = [[i,list(T[:,i])] for i in range(len(T[0,:]))]
        e_index = 0
        for i in range(1,len(p_index)):
            if p_index[i][1][0] < 0 and e_index == 0:
                e_index = i
        div_col = T[1:,0]
        piv_col = T[1:,e_index]
        if np.max(piv_col) <= 0:
            return False,False
        ind_col = [i for i in range(1,len(T))]
        ratios  = np.transpose(np.vstack((ind_col,div_col,piv_col)))
        ratios  = ratios[ratios[:,1] > 0]
        div = np.divide(ratios[:,1],ratios[:,e_index+1])
        div = np.array([[i] for i in div])
        ratios  = np.hstack((ratios,div))
        imax = np.argmax(ratios[:,3])
        return imax+1,e_index
    
    def solver(self,T,it_counter):
        if it_counter == 0:
            T = self.tableau(T)
        row,col = self.indexer(T)
        T[row,:] = T[row,:]/T[row,col]
        for i in range(len(T)):
            if i != row:
                k = T[i,col]/T[row,col]
                T[i,:] = T[i,:] - k*T[row,:]
        if all(i >= 0 for i in T[0,1:]) == True:
            return T
        else:
            return solver(self,T,it_counter + 1)
        
            
G = Prob1(b,c,w)
print("Problem #1")
print(G.cond_origin(A))
print("-----------------------------------------------------------------------------")
print("Problem #2")
print(G.slack_tracker(x))
print("-----------------------------------------------------------------------------")
print("Problem #3")
print(G.tableau(A))
print("-----------------------------------------------------------------------------")
print("Problem #4")
print(G.indexer(G.tableau(A)))
print("-----------------------------------------------------------------------------")
print("Problem #5")
print(G.solver(A,0))
print("-----------------------------------------------------------------------------")
print("Problem #6")
print("Answer included in above")
print("-----------------------------------------------------------------------------")
print("Problem #7")

Problem #1
True
-----------------------------------------------------------------------------
Problem #2
[[0 1]
 [1 1]
 [2 1]
 [3 3]
 [5 9]
 [4 0]]
-----------------------------------------------------------------------------
Problem #3
[[  0.  -4.  -3.  -6.   0.   0.   0.   1.]
 [ 40.   1.   5.   3.   1.   0.   0.   0.]
 [ 38.   8.   3.   2.   0.   1.   0.   0.]
 [ 21.   9.   5.   4.   0.   0.   1.   0.]]
-----------------------------------------------------------------------------
Problem #4
(1, 1)
-----------------------------------------------------------------------------
Problem #5
[[ 160.    0.   17.    6.    4.    0.    0.    1.]
 [  40.    1.    5.    3.    1.    0.    0.    0.]
 [-282.    0.  -37.  -22.   -8.    1.    0.    0.]
 [-339.    0.  -40.  -23.   -9.    0.    1.    0.]]
-----------------------------------------------------------------------------
Problem #6
Answer included in above
-----------------------------------------------------------------------------
Problem 