In [2]:
import numpy as np
import scipy.optimize as opt
import scipy.stats as st
import time

Part A: Use MLE and eqs 3,5 to find the optimal parameters

In [3]:
def normalpdf(x,mu,sigmasq):
    r = (1/np.sqrt(2*np.pi*(sigmasq)))*np.exp(-(((x - mu)**2)/(2*(sigmasq))))
    return r

def LLprob2(params,M,beta):
    mu,sigma,rho,alpha = params
    Z = np.log(M[:,2]/((1-alpha)*(M[:,1]**alpha)))
    Z_b = list(np.insert(Z,0,mu))
    del Z_b[-1]
    Zb = np.array(Z_b)
    pdf_vals = normalpdf(Z,(rho*Zb + (1 - rho)*mu),sigma**2)
    ln_pdf_vals = np.log(pdf_vals)
    log_lik_val = ln_pdf_vals.sum()
    return -log_lik_val

In [4]:
M = np.loadtxt("MacroSeries.txt", delimiter=",")
beta = 0.99

mu_i = 9.5
sigma_i = 0.5
rho_i = 0.55
alpha_i = 0.5
pmi = np.array([mu_i,sigma_i,rho_i,alpha_i])

cons = ({'type': 'ineq', 'fun': lambda x: pmi[0]},
        {'type': 'ineq', 'fun': lambda x: pmi[1]},
        {'type': 'ineq', 'fun': lambda x: -(pmi[2] - 1)},
        {'type': 'ineq', 'fun': lambda x: pmi[2] + 1},
        {'type': 'ineq', 'fun': lambda x: -(pmi[3] - 1)},
        {'type': 'ineq', 'fun': lambda x: pmi[3]}
        )

bounds = ((1e-10,None),(1e-10,None),(-1,1),(0,1))

mle_args = (M,beta)
start = time.time()
results = opt.minimize(LLprob2, pmi, args=(mle_args),method="BFGS", bounds=bounds)
print("Total Algorithm Duration: ",time.time()-start,"seconds")
print("Final Log-Likelyhood    : ",-results.fun)
print("   ")
mumle, sigmamle, rhomle, alphamle  = results.x
print("Mu (MLE)    :",mumle)
print("Sigma (MLE) :",sigmamle)
print("Rho (MLE)   :",rhomle)
print("Alpha (MLE) :",alphamle)
print(results.hess_inv)

Total Algorithm Duration:  0.07813858985900879 seconds
Final Log-Likelyhood    :  96.70690804456811
   
Mu (MLE)    : 9.52305109587
Sigma (MLE) : 0.0919961887029
Rho (MLE)   : 0.72050708169
Alpha (MLE) : 0.457492609413
[[  1.82636043e-02   9.05818232e-04  -1.73751513e-02  -1.35167433e-03]
 [  9.05818232e-04   1.04220020e-04  -8.74875186e-04  -6.80344252e-05]
 [ -1.73751513e-02  -8.74875186e-04   1.65328436e-02   1.28586287e-03]
 [ -1.35167433e-03  -6.80344252e-05   1.28586287e-03   1.05058914e-04]]


C:\Anaconda\lib\site-packages\scipy\optimize\_minimize.py:394: RuntimeWarning: Method BFGS cannot handle constraints nor bounds.
  RuntimeWarning)
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in log
  if sys.path[0] == '':
C:\Anaconda\lib\site-packages\scipy\optimize\optimize.py:628: RuntimeWarning: invalid value encountered in double_scalars
  grad[k] = (f(*((xk + d,) + args)) - f0) / d[k]
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in log
  if sys.path[0] == '':
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in log
  if sys.path[0] == '':
C:\Anaconda\lib\site-packages\scipy\optimize\optimize.py:628: RuntimeWarning: invalid value encountered in double_scalars
  grad[k] = (f(*((xk + d,) + args)) - f0) / d[k]
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in log
  if sys.path[0

Part B: Use equations 4 and five to estimate maximum likelihood.

In [42]:
def LLprob2_B(params,M,beta):
    mu,sigma,rho,alpha = params
    Z = np.log(M[:,3]/((alpha)*(M[:,1]**(alpha - 1))))
    Z_b = list(np.insert(Z,0,mu))
    del Z_b[-1]
    Zb = np.array(Z_b)
    pdf_vals = normalpdf(Z,(rho*Zb + (1 - rho)*mu),sigma**2)
    ln_pdf_vals = np.log(pdf_vals)
    log_lik_val = ln_pdf_vals.sum()
    return -log_lik_val

M = np.loadtxt("MacroSeries.txt", delimiter=",")
beta = 0.99

mu_i = 1.5
sigma_i = 0.5
rho_i = 0.55
alpha_i = 0.5
pmi = np.array([mu_i,sigma_i,rho_i,alpha_i])

cons = ({'type': 'ineq', 'fun': lambda x: pmi[0]},
        {'type': 'ineq', 'fun': lambda x: pmi[1]},
        {'type': 'ineq', 'fun': lambda x: -(pmi[2] - 1)},
        {'type': 'ineq', 'fun': lambda x: pmi[2] + 1},
        {'type': 'ineq', 'fun': lambda x: -(pmi[3] - 1)},
        {'type': 'ineq', 'fun': lambda x: pmi[3]}
        )

bounds = ((1e-10,None),(1e-10,None),(-1,1),(0,1))

mle_args = (M,beta)
start = time.time()
results2 = opt.minimize(LLprob2_B, pmi, args=(mle_args), method = "BFGS", bounds=bounds)
print("Total Algorithm Duration: ",time.time()-start,"seconds")
print("Final Log-Likelyhood    : ",-results2.fun)
print("   ")
mumle, sigmamle, rhomle, alphamle  = results2.x
print("Mu (MLE)    :",mumle)
print("Sigma (MLE) :",sigmamle)
print("Rho (MLE)   :",rhomle)
print("Alpha (MLE) :",alphamle)
print(results2.hess_inv)

Total Algorithm Duration:  0.11033105850219727 seconds
Final Log-Likelyhood    :  96.70690798977938
   
Mu (MLE)    : 9.37126803734
Sigma (MLE) : 0.0919966802033
Rho (MLE)   : 0.72052527987
Alpha (MLE) : 0.457462159627
[[  1.54865366e+01  -9.52734760e-04   6.03591452e-01  -8.59134224e-01]
 [ -9.52734760e-04   3.33515226e-05  -4.27694544e-05   5.35620318e-05]
 [  6.03591452e-01  -4.27694544e-05   2.78585173e-02  -3.34841946e-02]
 [ -8.59134224e-01   5.35620318e-05  -3.34841946e-02   4.76648215e-02]]


C:\Anaconda\lib\site-packages\scipy\optimize\_minimize.py:394: RuntimeWarning: Method BFGS cannot handle constraints nor bounds.
  RuntimeWarning)


Part C:

In [51]:
mu_g,sigma_g,rho_g,alpha_g = results.x

z_m1 = 10

def C_func(alpha,k,r):
    return np.log(r/((alpha)*(k**(alpha - 1))))

zstar = C_func(alpha_g,75000000,1)
zt    = rho_g * z_m1 + (1 - rho_g) * mu_g
zdiff = zstar - zt
prob = 1 - st.norm.cdf(zdiff)
print(prob)

0.22584991277
